import { Request, Response, NextFunction } from 'express';
import PDFDocument from 'pdfkit';
import * as XLSX from 'xlsx';
import QRCode from 'qrcode';
import { Receipt } from '../models/Receipt.js';
import { Invoice } from '../models/Invoice.js';
import { Transaction } from '../models/Transaction.js';
import { AppError } from '../utils/AppError.js';

function makeReceiptNumber() {
  return `RCT-${new Date().getFullYear()}-${Date.now().toString().slice(-6)}`;
}

async function streamReceiptPdf(receipt: any, res: Response) {
  const doc = new PDFDocument({ margin: 50 });
  const chunks: Buffer[] = [];
  doc.on('data', (chunk) => chunks.push(chunk));
  doc.on('end', () => {
    const result = Buffer.concat(chunks);
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=${receipt.receiptNumber}.pdf`);
    res.send(result);
  });
  doc.fontSize(22).text('ALAT Financial System');
  doc.moveDown(0.5).fontSize(18).text('PAYMENT RECEIPT', { align: 'right' });
  doc.moveDown();
  doc.fontSize(12).text(`Receipt No: ${receipt.receiptNumber}`);
  doc.text(`Customer: ${receipt.paidBy}`);
  doc.text(`Amount Paid: ${Number(receipt.amount || 0).toLocaleString()}`);
  doc.text(`Payment Method: ${receipt.paymentMethod || 'Not specified'}`);
  doc.text(`Date: ${new Date(receipt.issuedAt || receipt.createdAt).toLocaleDateString()}`);
  if (receipt.invoice?.invoiceNumber) doc.text(`Invoice: ${receipt.invoice.invoiceNumber}`);
  doc.moveDown();
  doc.fontSize(10).text('Thank you for your payment. This receipt was generated by ALAT Financial System.');
  doc.end();
}

export async function listReceipts(req: Request, res: Response, next: NextFunction) {
  try {
    const items = await Receipt.find({ business: req.user!.activeBusiness }).populate('invoice').sort({ createdAt: -1 }).limit(100);
    res.json({ success: true, data: items });
  } catch (e) { next(e); }
}

export async function createReceipt(req: Request, res: Response, next: NextFunction) {
  try {
    let amount = Number(req.body.amount || 0);
    let paidBy = req.body.paidBy || req.body.customerName || 'Customer';
    let invoice: any = null;
    if (req.body.invoiceId) {
      invoice = await Invoice.findOne({ _id: req.body.invoiceId, business: req.user!.activeBusiness });
      if (invoice) {
        amount = amount || invoice.total;
        paidBy = paidBy || invoice.clientName;
        await Invoice.findByIdAndUpdate(invoice._id, { status: 'paid' });
      }
    }
    if (!amount || amount <= 0) return next(new AppError(400, 'A valid payment amount is required'));
    const receiptNumber = req.body.receiptNumber || makeReceiptNumber();
    const qrCodeUrl = await QRCode.toDataURL(JSON.stringify({ receiptNumber, amount, paidBy }));
    const receipt = await Receipt.create({
      business: req.user!.activeBusiness,
      invoice: req.body.invoiceId,
      receiptNumber,
      amount,
      paidBy,
      paymentMethod: req.body.paymentMethod || 'Cash',
      qrCodeUrl,
      issuedAt: req.body.issuedAt || new Date()
    });
    await Transaction.create({ business: req.user!.activeBusiness, type: 'income', source: 'receipt', amount, description: `Receipt ${receiptNumber} - ${paidBy}`, referenceId: String(receipt._id) });
    res.status(201).json({ success: true, data: receipt });
  } catch (e) { next(e); }
}

export async function updateReceipt(req: Request, res: Response, next: NextFunction) {
  try {
    const receipt = await Receipt.findOneAndUpdate({ _id: req.params.id, business: req.user!.activeBusiness }, req.body, { new: true, runValidators: true });
    if (!receipt) return next(new AppError(404, 'Receipt not found'));
    await Transaction.findOneAndUpdate({ business: req.user!.activeBusiness, source: 'receipt', referenceId: String(receipt._id) }, { amount: receipt.amount, description: `Receipt ${receipt.receiptNumber} - ${receipt.paidBy}` });
    res.json({ success: true, data: receipt });
  } catch (e) { next(e); }
}

export async function deleteReceipt(req: Request, res: Response, next: NextFunction) {
  try {
    const receipt = await Receipt.findOneAndDelete({ _id: req.params.id, business: req.user!.activeBusiness });
    if (!receipt) return next(new AppError(404, 'Receipt not found'));
    await Transaction.deleteOne({ business: req.user!.activeBusiness, source: 'receipt', referenceId: String(receipt._id) });
    res.json({ success: true, message: 'Receipt deleted' });
  } catch (e) { next(e); }
}

export async function downloadReceiptPdf(req: Request, res: Response, next: NextFunction) {
  try {
    const receipt = await Receipt.findOne({ _id: req.params.id, business: req.user!.activeBusiness }).populate('invoice');
    if (!receipt) return next(new AppError(404, 'Receipt not found'));
    await streamReceiptPdf(receipt, res);
  } catch (e) { next(e); }
}

export async function downloadReceiptXlsx(req: Request, res: Response, next: NextFunction) {
  try {
    const receipt: any = await Receipt.findOne({ _id: req.params.id, business: req.user!.activeBusiness }).populate('invoice').lean();
    if (!receipt) return next(new AppError(404, 'Receipt not found'));
    const workbook = XLSX.utils.book_new();
    const sheet = XLSX.utils.json_to_sheet([{
      ReceiptNumber: receipt.receiptNumber,
      Customer: receipt.paidBy,
      Amount: receipt.amount,
      PaymentMethod: receipt.paymentMethod,
      Invoice: receipt.invoice?.invoiceNumber || '',
      Date: receipt.issuedAt || receipt.createdAt
    }]);
    XLSX.utils.book_append_sheet(workbook, sheet, 'Receipt');
    const buffer = XLSX.write(workbook, { type: 'buffer', bookType: 'xlsx' });
    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    res.setHeader('Content-Disposition', `attachment; filename=${receipt.receiptNumber}.xlsx`);
    res.send(buffer);
  } catch (e) { next(e); }
}
