import { useEffect, useState } from 'react';
import { View, Text, StyleSheet, ScrollView, TextInput, Pressable } from 'react-native';
import { api } from '../lib/api';
const money=(n:number)=>`₦${Number(n||0).toLocaleString()}`;
export default function Expenses(){
  const [items,setItems]=useState<any[]>([]); const [summary,setSummary]=useState<any>({}); const [title,setTitle]=useState(''); const [amount,setAmount]=useState('');
  async function load(){try{const [a,b]=await Promise.all([api.get('/expenses'),api.get('/expenses/summary')]);setItems(a.data.data.items||[]);setSummary(b.data.data||{})}catch{}}
  useEffect(()=>{load()},[]);
  async function add(){if(!title||Number(amount)<=0)return; await api.post('/expenses',{title,amount:Number(amount),category:'Miscellaneous'}); setTitle(''); setAmount(''); load();}
  return <ScrollView style={s.container}><Text style={s.title}>Expense Tracking</Text><View style={s.row}><Card label="Income" value={money(summary.totalIncome)}/><Card label="Expenses" value={money(summary.totalExpenses)}/></View><View style={s.row}><Card label="Net" value={money(summary.netBalance)}/><Card label="Profit" value={money(summary.profit)}/></View><View style={s.form}><TextInput placeholder="Expense title" placeholderTextColor="#64748b" value={title} onChangeText={setTitle} style={s.input}/><TextInput placeholder="Amount" placeholderTextColor="#64748b" value={amount} onChangeText={setAmount} keyboardType="numeric" style={s.input}/><Pressable onPress={add} style={s.btn}><Text style={s.btnText}>Add Expense</Text></Pressable></View>{items.map(i=><View key={i._id} style={s.card}><Text style={s.name}>{i.title}</Text><Text style={s.text}>{i.category} · {money(i.amount)}</Text></View>)}</ScrollView>}
function Card({label,value}:any){return <View style={s.metric}><Text style={s.text}>{label}</Text><Text style={s.metricText}>{value}</Text></View>}
const s=StyleSheet.create({container:{flex:1,backgroundColor:'#170C79',padding:20},title:{color:'#fff',fontSize:26,fontWeight:'800'},row:{flexDirection:'row',gap:10,marginTop:12},metric:{flex:1,backgroundColor:'rgba(255,255,255,0.10)',padding:14,borderRadius:18},metricText:{color:'#56B6C6',fontWeight:'900',fontSize:17,marginTop:6},form:{marginTop:16,gap:10},input:{backgroundColor:'rgba(255,255,255,0.10)',color:'#fff',padding:14,borderRadius:16},btn:{backgroundColor:'#56B6C6',padding:14,borderRadius:16,alignItems:'center'},btnText:{fontWeight:'900',color:'#170C79'},card:{marginTop:14,backgroundColor:'rgba(255,255,255,0.10)',padding:16,borderRadius:18},name:{color:'#fff',fontWeight:'800'},text:{color:'#EFE3CA',marginTop:6}});
