import { Router } from 'express';
import { requireAuth } from '../middlewares/auth.js';
import { addClient, addProject, businessPerformance, createBusiness, deleteBusiness, listBusinesses, updateBusiness } from '../controllers/business.controller.js';
const router = Router();
router.use(requireAuth);
router.route('/').get(listBusinesses).post(createBusiness);
router.get('/:id/performance', businessPerformance);
router.post('/:id/clients', addClient);
router.post('/:id/projects', addProject);
router.route('/:id').patch(updateBusiness).delete(deleteBusiness);
export default router;
