import { Router } from 'express';
import { requireAuth } from '../middlewares/auth.js';
import { createExpense, createIncome, deleteExpense, deleteIncome, expenseSummary, listExpenses, listIncome, updateExpense, updateIncome } from '../controllers/expense.controller.js';
const router = Router();
router.use(requireAuth);
router.get('/summary', expenseSummary);
router.route('/income').get(listIncome).post(createIncome);
router.route('/income/:id').patch(updateIncome).delete(deleteIncome);
router.route('/').get(listExpenses).post(createExpense);
router.route('/:id').patch(updateExpense).delete(deleteExpense);
export default router;
