import { Router } from 'express';
import { requireAuth } from '../middlewares/auth.js';
import { createInvoice, deleteInvoice, downloadInvoicePdf, downloadInvoiceXlsx, listInvoices, updateInvoice } from '../controllers/invoice.controller.js';
const router = Router();
router.use(requireAuth);
router.route('/').get(listInvoices).post(createInvoice);
router.get('/:id/pdf', downloadInvoicePdf);
router.get('/:id/xlsx', downloadInvoiceXlsx);
router.route('/:id').patch(updateInvoice).delete(deleteInvoice);
export default router;
