import { useEffect, useMemo, useState } from 'react';
import { motion } from 'framer-motion';
import { BriefcaseBusiness, Plus, Trash2, Users } from 'lucide-react';
import { api } from '../lib/api';
const money=(n:number)=>`₦${Number(n||0).toLocaleString()}`;
export default function Businesses(){
  const [businesses,setBusinesses]=useState<any[]>([]); const [employees,setEmployees]=useState<any[]>([]); const [selected,setSelected]=useState<any|null>(null); const [performance,setPerformance]=useState<any>({}); const [error,setError]=useState('');
  const [businessForm,setBusinessForm]=useState({name:'',industry:'',email:'',phone:'',address:'',currency:'NGN'});
  const [clientForm,setClientForm]=useState({name:'',email:'',phone:'',address:''});
  const [projectForm,setProjectForm]=useState({name:'',clientName:'',budget:'',status:'active',description:''});
  const [staffForm,setStaffForm]=useState({name:'',email:'',department:'Operations',role:'Staff',salary:'',status:'active'});
  async function load(){try{const [b,e]=await Promise.all([api.get('/businesses'),api.get('/employees')]); const items=b.data.data||[]; setBusinesses(items); setEmployees(e.data.data||[]); const active=selected?items.find((x:any)=>x._id===selected._id):items[0]; setSelected(active||null); if(active){const perf=await api.get(`/businesses/${active._id}/performance`); setPerformance(perf.data.data||{})}}catch(err:any){setError(err?.response?.data?.message||'Unable to load business data.')}}
  useEffect(()=>{load()},[]);
  useEffect(()=>{if(selected){api.get(`/businesses/${selected._id}/performance`).then(r=>setPerformance(r.data.data||{})).catch(()=>undefined)}},[selected?._id]);
  const payroll=useMemo(()=>employees.reduce((s,e)=>s+Number(e.salary||0),0),[employees]);
  async function createBusiness(e:React.FormEvent){e.preventDefault();try{if(!businessForm.name) throw new Error('Business name is required.'); await api.post('/businesses',businessForm); setBusinessForm({name:'',industry:'',email:'',phone:'',address:'',currency:'NGN'}); load()}catch(err:any){setError(err?.response?.data?.message||err.message)}}
  async function addClient(e:React.FormEvent){e.preventDefault(); if(!selected) return; try{await api.post(`/businesses/${selected._id}/clients`,clientForm); setClientForm({name:'',email:'',phone:'',address:''}); load()}catch(err:any){setError(err?.response?.data?.message||err.message)}}
  async function addProject(e:React.FormEvent){e.preventDefault(); if(!selected) return; try{await api.post(`/businesses/${selected._id}/projects`,{...projectForm,budget:Number(projectForm.budget)}); setProjectForm({name:'',clientName:'',budget:'',status:'active',description:''}); load()}catch(err:any){setError(err?.response?.data?.message||err.message)}}
  async function addStaff(e:React.FormEvent){e.preventDefault(); try{await api.post('/employees',{...staffForm,salary:Number(staffForm.salary)}); setStaffForm({name:'',email:'',department:'Operations',role:'Staff',salary:'',status:'active'}); load()}catch(err:any){setError(err?.response?.data?.message||err.message)}}
  async function deleteBusiness(id:string){if(confirm('Delete this business?')){await api.delete(`/businesses/${id}`); setSelected(null); load()}}
  async function deleteEmployee(id:string){if(confirm('Delete this worker?')){await api.delete(`/employees/${id}`); load()}}
  return <div className="space-y-6"><div><p className="text-sm uppercase tracking-[0.3em] text-[#8ACBD0]">Company operations</p><h1 className="mt-2 text-3xl font-black md:text-4xl">Business Management</h1><p className="mt-2 max-w-3xl text-slate-300">Manage multiple businesses, clients, workers, salaries, projects, and financial performance per company.</p></div>{error&&<p className="rounded-2xl bg-red-500/15 p-4 text-red-100">{error}</p>}
  <section className="grid gap-4 md:grid-cols-4"><Metric title="Businesses" value={businesses.length}/><Metric title="Workers" value={employees.length}/><Metric title="Monthly Salaries" value={money(payroll)}/><Metric title="Net Performance" value={money(performance.netBalance)}/></section>
  <section className="grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><motion.form initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} onSubmit={createBusiness} className="card p-5"><h2 className="text-xl font-black">Add Business</h2><div className="mt-4 grid gap-3"><input className="input" placeholder="Business name" value={businessForm.name} onChange={e=>setBusinessForm({...businessForm,name:e.target.value})}/><input className="input" placeholder="Industry" value={businessForm.industry} onChange={e=>setBusinessForm({...businessForm,industry:e.target.value})}/><input className="input" placeholder="Email" value={businessForm.email} onChange={e=>setBusinessForm({...businessForm,email:e.target.value})}/><input className="input" placeholder="Phone" value={businessForm.phone} onChange={e=>setBusinessForm({...businessForm,phone:e.target.value})}/><input className="input" placeholder="Address" value={businessForm.address} onChange={e=>setBusinessForm({...businessForm,address:e.target.value})}/></div><button className="btn mt-4"><Plus size={16}/> Save Business</button></motion.form><div className="card p-5"><h2 className="text-xl font-black">Business Portfolio</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{businesses.map((b:any)=><button key={b._id} onClick={()=>setSelected(b)} className={`rounded-3xl border p-4 text-left transition ${selected?._id===b._id?'border-[#8ACBD0] bg-[#56B6C6]/20':'border-white/10 bg-white/5 hover:bg-white/10'}`}><div className="flex items-start justify-between"><BriefcaseBusiness className="text-[#8ACBD0]"/><span onClick={(e)=>{e.stopPropagation();deleteBusiness(b._id)}} className="rounded-xl bg-red-500/15 px-2 py-1 text-xs text-red-100">Delete</span></div><h3 className="mt-3 font-black">{b.name}</h3><p className="text-sm text-slate-300">{b.industry||'General business'}</p><p className="mt-2 text-xs text-slate-400">{b.email||'No email'} · {b.currency}</p></button>)}</div></div></section>
  {selected&&<section className="grid gap-6 xl:grid-cols-3"><Form title="Add Client" onSubmit={addClient}><input className="input" placeholder="Name" value={clientForm.name} onChange={e=>setClientForm({...clientForm,name:e.target.value})}/><input className="input" placeholder="Email" value={clientForm.email} onChange={e=>setClientForm({...clientForm,email:e.target.value})}/><input className="input" placeholder="Phone" value={clientForm.phone} onChange={e=>setClientForm({...clientForm,phone:e.target.value})}/><input className="input" placeholder="Address" value={clientForm.address} onChange={e=>setClientForm({...clientForm,address:e.target.value})}/></Form><Form title="Add Worker" onSubmit={addStaff}><input className="input" placeholder="Name" value={staffForm.name} onChange={e=>setStaffForm({...staffForm,name:e.target.value})}/><input className="input" placeholder="Email" value={staffForm.email} onChange={e=>setStaffForm({...staffForm,email:e.target.value})}/><input className="input" placeholder="Department" value={staffForm.department} onChange={e=>setStaffForm({...staffForm,department:e.target.value})}/><input className="input" placeholder="Role" value={staffForm.role} onChange={e=>setStaffForm({...staffForm,role:e.target.value})}/><input className="input" type="number" placeholder="Salary" value={staffForm.salary} onChange={e=>setStaffForm({...staffForm,salary:e.target.value})}/></Form><Form title="Add Project / Service" onSubmit={addProject}><input className="input" placeholder="Project name" value={projectForm.name} onChange={e=>setProjectForm({...projectForm,name:e.target.value})}/><input className="input" placeholder="Client name" value={projectForm.clientName} onChange={e=>setProjectForm({...projectForm,clientName:e.target.value})}/><input className="input" type="number" placeholder="Budget" value={projectForm.budget} onChange={e=>setProjectForm({...projectForm,budget:e.target.value})}/><select className="input" value={projectForm.status} onChange={e=>setProjectForm({...projectForm,status:e.target.value})}><option value="active">Active</option><option value="planned">Planned</option><option value="completed">Completed</option><option value="paused">Paused</option></select></Form></section>}
  {selected&&<section className="grid gap-6 xl:grid-cols-2"><List title="Clients" rows={selected.clients||[]} fields={['name','email','phone']}/><List title="Projects / Services" rows={selected.projects||[]} fields={['name','clientName','status','budget']}/><div className="card overflow-hidden xl:col-span-2"><div className="p-5 font-black">Workers & Salaries</div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="table-head"><tr><th className="p-3">Name</th><th className="p-3">Email</th><th className="p-3">Department</th><th className="p-3">Role</th><th className="p-3">Salary</th><th className="p-3">Action</th></tr></thead><tbody>{employees.map((w:any)=><tr key={w._id} className="border-t border-white/10"><td className="p-3">{w.name}</td><td className="p-3">{w.email}</td><td className="p-3">{w.department}</td><td className="p-3">{w.role}</td><td className="p-3">{money(w.salary)}</td><td className="p-3"><button onClick={()=>deleteEmployee(w._id)} className="btn-danger"><Trash2 size={14}/></button></td></tr>)}</tbody></table></div></div></section>}
  </div>
}
function Metric({title,value}:any){return <div className="card p-5"><p className="text-sm text-slate-300">{title}</p><h3 className="mt-2 text-2xl font-black text-[#8ACBD0]">{value}</h3></div>}
function Form({title,onSubmit,children}:any){return <form onSubmit={onSubmit} className="card p-5"><h2 className="font-black">{title}</h2><div className="mt-4 space-y-3">{children}</div><button className="btn mt-4"><Plus size={14}/> Add</button></form>}
function List({title,rows,fields}:any){return <div className="card p-5"><h2 className="flex items-center gap-2 font-black"><Users size={18}/>{title}</h2><div className="mt-4 space-y-3">{rows.length?rows.map((r:any)=><div key={r._id||r.name} className="rounded-2xl bg-white/10 p-3 text-sm">{fields.map((f:string)=><span key={f} className="mr-3"><b>{f}:</b> {f==='budget'?money(r[f]):r[f]||'—'}</span>)}</div>):<p className="text-sm text-slate-400">No records yet.</p>}</div></div>}
