import { useEffect, useMemo, useState } from 'react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { api } from '../lib/api';
import { ArrowDownRight, ArrowUpRight, Brain, Building2, FileText, ReceiptText } from 'lucide-react';
const money=(n:number)=>`₦${Number(n||0).toLocaleString()}`;
export default function Dashboard(){
  const [summary,setSummary]=useState<any>({}); const [invoices,setInvoices]=useState<any[]>([]); const [receipts,setReceipts]=useState<any[]>([]); const [businesses,setBusinesses]=useState<any[]>([]); const [error,setError]=useState('');
  async function load(){try{const [s,i,r,b]=await Promise.all([api.get('/expenses/summary'),api.get('/invoices'),api.get('/receipts'),api.get('/businesses')]);setSummary(s.data.data);setInvoices(i.data.data.items||[]);setReceipts(r.data.data||[]);setBusinesses(b.data.data||[])}catch(e:any){setError(e?.response?.data?.message||'Unable to load dashboard data.')}}
  useEffect(()=>{load()},[]);
  const invoiceTotal=useMemo(()=>invoices.reduce((s:any,x:any)=>s+Number(x.total||0),0),[invoices]);
  return <div className="space-y-6">
    <div className="grid gap-6 xl:grid-cols-[1.5fr_.9fr]"><section className="card overflow-hidden p-6"><p className="text-sm uppercase tracking-[0.3em] text-[#8ACBD0]">Financial command center</p><h1 className="mt-2 max-w-3xl text-4xl font-black md:text-5xl">Run expenses, income, invoices and business performance from one premium dashboard.</h1><p className="mt-4 max-w-2xl text-slate-300">Production-ready MERN financial management with MongoDB persistence, downloads, analytics, PWA support, and AI guidance.</p>{error&&<p className="mt-4 rounded-2xl bg-red-500/15 p-3 text-red-100">{error}</p>}</section><section className="card p-6"><Brain className="text-[#8ACBD0]"/><h2 className="mt-4 text-xl font-black">AI Insight</h2><p className="mt-2 text-sm text-slate-300">{summary.aiInsight || 'Add income and expenses to generate AI-powered financial recommendations.'}</p></section></div>
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Metric icon={<ArrowUpRight/>} title="Income" value={money(summary.totalIncome)}/><Metric icon={<ArrowDownRight/>} title="Expenses" value={money(summary.totalExpenses)}/><Metric icon={<FileText/>} title="Invoice Pipeline" value={money(invoiceTotal)}/><Metric icon={<ReceiptText/>} title="Receipts" value={String(receipts.length)}/></section>
    <section className="grid gap-6 xl:grid-cols-2"><div className="card p-5"><h2 className="font-black">Income vs Expenses</h2><div className="mt-4 h-80"><ResponsiveContainer><AreaChart data={summary.monthly||[]}><CartesianGrid strokeDasharray="3 3" opacity={.2}/><XAxis dataKey="month"/><YAxis/><Tooltip/><Area type="monotone" dataKey="income" stroke="#8ACBD0" fill="#8ACBD0" fillOpacity={.25}/><Area type="monotone" dataKey="expenses" stroke="#EFE3CA" fill="#EFE3CA" fillOpacity={.2}/></AreaChart></ResponsiveContainer></div></div><div className="card p-5"><h2 className="font-black">Top Categories</h2><div className="mt-4 h-80"><ResponsiveContainer><BarChart data={summary.expensesByCategory||[]}><CartesianGrid strokeDasharray="3 3" opacity={.2}/><XAxis dataKey="_id"/><YAxis/><Tooltip/><Bar dataKey="total" fill="#56B6C6" radius={[12,12,0,0]}/></BarChart></ResponsiveContainer></div></div></section>
    <section className="grid gap-6 lg:grid-cols-3"><Mini title="Businesses" icon={<Building2/>} items={businesses.map((b:any)=>b.name)}/><Mini title="Recent Invoices" icon={<FileText/>} items={invoices.slice(0,5).map((i:any)=>`${i.invoiceNumber} · ${money(i.total)}`)}/><Mini title="Recent Receipts" icon={<ReceiptText/>} items={receipts.slice(0,5).map((r:any)=>`${r.receiptNumber} · ${money(r.amount)}`)}/></section>
  </div>
}
function Metric({title,value,icon}:any){return <div className="card p-5"><div className="flex items-center justify-between"><span className="text-sm text-slate-300">{title}</span><span className="rounded-2xl bg-[#56B6C6]/15 p-2 text-[#8ACBD0]">{icon}</span></div><h3 className="mt-4 text-3xl font-black">{value}</h3></div>}
function Mini({title,items,icon}:any){return <div className="card p-5"><div className="flex items-center gap-2 font-black text-[#8ACBD0]">{icon}{title}</div><div className="mt-4 space-y-3">{items.length?items.map((x:string)=><div key={x} className="rounded-2xl bg-white/10 p-3 text-sm">{x}</div>):<p className="text-sm text-slate-400">No data yet.</p>}</div></div>}
