import { useEffect, useMemo, useState } from 'react';
import { motion } from 'framer-motion';
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Brain, Pencil, Plus, Trash2 } from 'lucide-react';
import { api } from '../lib/api';

const defaultCategories = ['Transportation','Utilities','Salaries','Maintenance','Marketing','Rent','Miscellaneous'];
const money=(n:number)=>`₦${Number(n||0).toLocaleString()}`;
const today=()=>new Date().toISOString().slice(0,10);

export default function Expenses(){
  const [expenses,setExpenses]=useState<any[]>([]); const [income,setIncome]=useState<any[]>([]); const [summary,setSummary]=useState<any>({}); const [error,setError]=useState(''); const [saving,setSaving]=useState(false);
  const [editingExpense,setEditingExpense]=useState<string|null>(null); const [editingIncome,setEditingIncome]=useState<string|null>(null); const [customCategory,setCustomCategory]=useState('');
  const [expenseForm,setExpenseForm]=useState({title:'',amount:'',category:'Miscellaneous',department:'',vendor:'',date:today(),description:''});
  const [incomeForm,setIncomeForm]=useState({description:'',amount:'',source:'Sales',date:today()});
  async function load(){try{const [e,i,s]=await Promise.all([api.get('/expenses?limit=100'),api.get('/expenses/income?limit=100'),api.get('/expenses/summary')]);setExpenses(e.data.data.items||[]);setIncome(i.data.data.items||[]);setSummary(s.data.data||{});setError('')}catch(err:any){setError(err?.response?.data?.message||'Unable to load expense data.')}}
  useEffect(()=>{load()},[]);
  const categories=useMemo(()=>Array.from(new Set([...defaultCategories,...expenses.map((x:any)=>x.category).filter(Boolean)])),[expenses]);
  const pieData=useMemo(()=>(summary.expensesByCategory||[]).map((x:any)=>({name:x._id,value:x.total})),[summary]);
  async function saveExpense(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');try{const payload={...expenseForm,category:customCategory.trim()||expenseForm.category,amount:Number(expenseForm.amount)}; if(!payload.title||payload.amount<=0) throw new Error('Enter expense title and a valid amount.'); if(editingExpense){await api.patch(`/expenses/${editingExpense}`,payload)}else{await api.post('/expenses',payload)} setEditingExpense(null); setCustomCategory(''); setExpenseForm({title:'',amount:'',category:'Miscellaneous',department:'',vendor:'',date:today(),description:''}); await load()}catch(err:any){setError(err?.response?.data?.message||err.message)}finally{setSaving(false)}}
  async function saveIncome(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');try{const payload={...incomeForm,amount:Number(incomeForm.amount)}; if(!payload.description||payload.amount<=0) throw new Error('Enter income description and a valid amount.'); if(editingIncome){await api.patch(`/expenses/income/${editingIncome}`,payload)}else{await api.post('/expenses/income',payload)} setEditingIncome(null); setIncomeForm({description:'',amount:'',source:'Sales',date:today()}); await load()}catch(err:any){setError(err?.response?.data?.message||err.message)}finally{setSaving(false)}}
  function editExpense(row:any){setEditingExpense(row._id);setExpenseForm({title:row.title||'',amount:String(row.amount||''),category:row.category||'Miscellaneous',department:row.department||'',vendor:row.vendor||'',date:new Date(row.date).toISOString().slice(0,10),description:row.description||''}); window.scrollTo({top:0,behavior:'smooth'})}
  function editIncome(row:any){setEditingIncome(row._id);setIncomeForm({description:row.description||'',amount:String(row.amount||''),source:row.source||'Sales',date:new Date(row.date).toISOString().slice(0,10)}); window.scrollTo({top:0,behavior:'smooth'})}
  async function removeExpense(id:string){if(confirm('Delete this expense?')){await api.delete(`/expenses/${id}`);load()}}
  async function removeIncome(id:string){if(confirm('Delete this income record?')){await api.delete(`/expenses/income/${id}`);load()}}
  return <div className="space-y-6"><Header title="Expenses Management" subtitle="Create income and expense records, calculate profit/loss automatically, and analyze cash movement with AI recommendations." />
    {error&&<div className="rounded-2xl border border-red-400/30 bg-red-500/10 p-4 text-red-100">{error}</div>}
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-5"><Metric title="Total Income" value={money(summary.totalIncome)}/><Metric title="Total Expenses" value={money(summary.totalExpenses)}/><Metric title="Profit" value={money(summary.profit)}/><Metric title="Loss" value={money(summary.loss)} danger={summary.loss>0}/><Metric title="Net Balance" value={money(summary.netBalance)} danger={summary.netBalance<0}/></section>
    <section className="grid gap-6 xl:grid-cols-[1fr_.9fr]"><motion.form initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} onSubmit={saveExpense} className="card p-5"><div className="flex items-center justify-between"><h2 className="text-xl font-black">{editingExpense?'Edit Expense':'Add Expense'}</h2>{editingExpense&&<button type="button" onClick={()=>setEditingExpense(null)} className="btn-secondary">Cancel</button>}</div><div className="mt-4 grid gap-3 md:grid-cols-2"><input className="input" placeholder="Expense title" value={expenseForm.title} onChange={e=>setExpenseForm({...expenseForm,title:e.target.value})}/><input className="input" type="number" placeholder="Amount" value={expenseForm.amount} onChange={e=>setExpenseForm({...expenseForm,amount:e.target.value})}/><select className="input" value={expenseForm.category} onChange={e=>setExpenseForm({...expenseForm,category:e.target.value})}>{categories.map(c=><option key={c}>{c}</option>)}</select><input className="input" placeholder="Custom category optional" value={customCategory} onChange={e=>setCustomCategory(e.target.value)}/><input className="input" placeholder="Department" value={expenseForm.department} onChange={e=>setExpenseForm({...expenseForm,department:e.target.value})}/><input className="input" placeholder="Vendor / recipient" value={expenseForm.vendor} onChange={e=>setExpenseForm({...expenseForm,vendor:e.target.value})}/><input className="input" type="date" value={expenseForm.date} onChange={e=>setExpenseForm({...expenseForm,date:e.target.value})}/><input className="input" placeholder="Notes" value={expenseForm.description} onChange={e=>setExpenseForm({...expenseForm,description:e.target.value})}/></div><button disabled={saving} className="btn mt-4"><Plus size={16}/>{editingExpense?'Update Expense':'Save Expense'}</button></motion.form>
    <form onSubmit={saveIncome} className="card p-5"><div className="flex items-center justify-between"><h2 className="text-xl font-black">{editingIncome?'Edit Income':'Add Income'}</h2>{editingIncome&&<button type="button" onClick={()=>setEditingIncome(null)} className="btn-secondary">Cancel</button>}</div><div className="mt-4 grid gap-3"><input className="input" placeholder="Income description" value={incomeForm.description} onChange={e=>setIncomeForm({...incomeForm,description:e.target.value})}/><input className="input" type="number" placeholder="Amount" value={incomeForm.amount} onChange={e=>setIncomeForm({...incomeForm,amount:e.target.value})}/><input className="input" placeholder="Source e.g. sales, consulting" value={incomeForm.source} onChange={e=>setIncomeForm({...incomeForm,source:e.target.value})}/><input className="input" type="date" value={incomeForm.date} onChange={e=>setIncomeForm({...incomeForm,date:e.target.value})}/></div><button disabled={saving} className="btn mt-4"><Plus size={16}/>{editingIncome?'Update Income':'Save Income'}</button></form></section>
    <section className="grid gap-6 xl:grid-cols-2"><ChartCard title="Monthly Income vs Expense"><ResponsiveContainer><BarChart data={summary.monthly||[]}><CartesianGrid strokeDasharray="3 3" opacity={.2}/><XAxis dataKey="month"/><YAxis/><Tooltip/><Bar dataKey="income" fill="#8ACBD0" radius={[10,10,0,0]}/><Bar dataKey="expenses" fill="#EFE3CA" radius={[10,10,0,0]}/></BarChart></ResponsiveContainer></ChartCard><ChartCard title="Spending by Category"><ResponsiveContainer><PieChart><Pie data={pieData} dataKey="value" nameKey="name" outerRadius={100} label>{pieData.map((_:any,i:number)=><Cell key={i} fill={['#56B6C6','#8ACBD0','#EFE3CA','#ffffff','#948be8'][i%5]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></ChartCard></section>
    <section className="card p-5"><div className="flex gap-3"><Brain className="text-[#8ACBD0]"/><div><h2 className="font-black">AI Financial Insight</h2><p className="mt-1 text-sm text-slate-300">{summary.aiInsight}</p></div></div></section>
    <section className="grid gap-6 xl:grid-cols-2"><Records title="Expenses" rows={expenses} columns={[['title','Title'],['category','Category'],['department','Department'],['amount','Amount'],['riskScore','Risk']]} onEdit={editExpense} onDelete={removeExpense}/><Records title="Income" rows={income} columns={[['description','Description'],['source','Source'],['amount','Amount'],['date','Date']]} onEdit={editIncome} onDelete={removeIncome}/></section>
  </div>
}
function Header({title,subtitle}:any){return <div><p className="text-sm uppercase tracking-[0.3em] text-[#8ACBD0]">Financial operations</p><h1 className="mt-2 text-3xl font-black md:text-4xl">{title}</h1><p className="mt-2 max-w-3xl text-slate-300">{subtitle}</p></div>}
function Metric({title,value,danger}:any){return <div className="card p-5"><p className="text-sm text-slate-300">{title}</p><h3 className={`mt-2 text-2xl font-black ${danger?'text-red-200':'text-[#8ACBD0]'}`}>{value}</h3></div>}
function ChartCard({title,children}:any){return <div className="card p-5"><h2 className="font-black">{title}</h2><div className="mt-4 h-80">{children}</div></div>}
function Records({title,rows,columns,onEdit,onDelete}:any){return <div className="card overflow-hidden"><div className="p-5 font-black">{title}</div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="table-head"><tr>{columns.map(([,label]:any)=><th key={label} className="p-3">{label}</th>)}<th className="p-3">Actions</th></tr></thead><tbody>{rows.length?rows.map((row:any)=><tr key={row._id} className="border-t border-white/10">{columns.map(([key]:any)=><td key={key} className="p-3">{key==='amount'?money(row[key]):key==='date'?new Date(row[key]).toLocaleDateString():row[key]||'—'}</td>)}<td className="flex gap-2 p-3"><button onClick={()=>onEdit(row)} className="btn-secondary px-3 py-2"><Pencil size={14}/></button><button onClick={()=>onDelete(row._id)} className="btn-danger"><Trash2 size={14}/></button></td></tr>):<tr><td className="p-6 text-slate-400" colSpan={columns.length+1}>No records yet. Create your first record above.</td></tr>}</tbody></table></div></div>}
