import { useEffect, useMemo, useState } from 'react';
import { motion } from 'framer-motion';
import { Download, FileSpreadsheet, Plus, Printer, Trash2 } from 'lucide-react';
import { api } from '../lib/api';
const money=(n:number)=>`₦${Number(n||0).toLocaleString()}`; const today=()=>new Date().toISOString().slice(0,10);
function downloadBlob(url:string, name:string){api.get(url,{responseType:'blob'}).then(res=>{const blob=new Blob([res.data]); const link=document.createElement('a'); link.href=URL.createObjectURL(blob); link.download=name; link.click(); URL.revokeObjectURL(link.href);});}
export default function Invoices(){
  const [invoices,setInvoices]=useState<any[]>([]); const [error,setError]=useState(''); const [saving,setSaving]=useState(false); const [items,setItems]=useState([{description:'Consulting service',quantity:1,unitPrice:0}]);
  const [form,setForm]=useState({clientName:'',clientEmail:'',clientAddress:'',tax:'0',discount:'0',dueDate:today(),status:'pending',notes:''});
  async function load(){try{const res=await api.get('/invoices?limit=100');setInvoices(res.data.data.items||[])}catch(e:any){setError(e?.response?.data?.message||'Unable to load invoices.')}}
  useEffect(()=>{load()},[]);
  const subtotal=useMemo(()=>items.reduce((s,i)=>s+Number(i.quantity||0)*Number(i.unitPrice||0),0),[items]); const total=Math.max(subtotal+Number(form.tax||0)-Number(form.discount||0),0);
  function setItem(i:number,key:string,value:any){setItems(rows=>rows.map((r,idx)=>idx===i?{...r,[key]:key==='description'?value:Number(value)}:r));}
  async function save(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');try{if(!form.clientName) throw new Error('Client name is required.'); if(total<=0) throw new Error('Invoice total must be greater than zero.'); await api.post('/invoices',{...form,tax:Number(form.tax),discount:Number(form.discount),items}); setForm({clientName:'',clientEmail:'',clientAddress:'',tax:'0',discount:'0',dueDate:today(),status:'pending',notes:''}); setItems([{description:'Consulting service',quantity:1,unitPrice:0}]); await load();}catch(err:any){setError(err?.response?.data?.message||err.message)}finally{setSaving(false)}}
  async function remove(id:string){if(confirm('Delete this invoice?')){await api.delete(`/invoices/${id}`);load()}}
  return <div className="space-y-6"><div><p className="text-sm uppercase tracking-[0.3em] text-[#8ACBD0]">Billing</p><h1 className="mt-2 text-3xl font-black md:text-4xl">Invoice Management</h1><p className="mt-2 max-w-3xl text-slate-300">Generate professional customer invoices with auto totals, VAT/tax, discounts, PDF export, Excel export and printable layouts.</p></div>{error&&<p className="rounded-2xl bg-red-500/15 p-4 text-red-100">{error}</p>}
  <section className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><motion.form initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} onSubmit={save} className="card p-5"><h2 className="text-xl font-black">Create New Invoice</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><input className="input" placeholder="Client / customer name" value={form.clientName} onChange={e=>setForm({...form,clientName:e.target.value})}/><input className="input" placeholder="Client email" value={form.clientEmail} onChange={e=>setForm({...form,clientEmail:e.target.value})}/><input className="input md:col-span-2" placeholder="Client address" value={form.clientAddress} onChange={e=>setForm({...form,clientAddress:e.target.value})}/></div><div className="mt-5 space-y-3"><div className="flex items-center justify-between"><h3 className="font-bold">Products / Services</h3><button type="button" onClick={()=>setItems([...items,{description:'',quantity:1,unitPrice:0}])} className="btn-secondary"><Plus size={14}/> Add row</button></div>{items.map((item,i)=><div key={i} className="grid gap-3 rounded-3xl border border-white/10 bg-white/5 p-3 md:grid-cols-[1fr_120px_160px_50px]"><input className="input" placeholder="Product or service" value={item.description} onChange={e=>setItem(i,'description',e.target.value)}/><input className="input" type="number" min="1" placeholder="Qty" value={item.quantity} onChange={e=>setItem(i,'quantity',e.target.value)}/><input className="input" type="number" min="0" placeholder="Unit price" value={item.unitPrice} onChange={e=>setItem(i,'unitPrice',e.target.value)}/><button type="button" onClick={()=>setItems(items.filter((_,idx)=>idx!==i))} className="btn-danger"><Trash2 size={14}/></button></div>)}</div><div className="mt-4 grid gap-3 md:grid-cols-4"><input className="input" type="number" placeholder="Tax/VAT" value={form.tax} onChange={e=>setForm({...form,tax:e.target.value})}/><input className="input" type="number" placeholder="Discount" value={form.discount} onChange={e=>setForm({...form,discount:e.target.value})}/><input className="input" type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/><select className="input" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="pending">Pending</option><option value="paid">Paid</option><option value="overdue">Overdue</option></select></div><textarea className="input mt-3 min-h-24" placeholder="Notes" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><button disabled={saving} className="btn mt-4">Generate Invoice</button></motion.form>
  <aside className="card p-5"><h2 className="text-xl font-black">Live Invoice Preview</h2><div className="mt-4 rounded-[2rem] bg-[#EFE3CA] p-5 text-[#170C79]"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-widest">ALAT Financial System</p><h3 className="mt-1 text-2xl font-black">INVOICE</h3></div><span className="rounded-full bg-[#170C79] px-3 py-1 text-xs font-bold text-white">{form.status}</span></div><div className="mt-6 text-sm"><p className="font-bold">Bill To</p><p>{form.clientName||'Client name'}</p><p>{form.clientEmail||'client@email.com'}</p></div><div className="mt-5 space-y-2 text-sm">{items.map((i,idx)=><div className="flex justify-between border-b border-[#170C79]/20 pb-2" key={idx}><span>{i.description||'Service'} × {i.quantity}</span><b>{money(Number(i.quantity)*Number(i.unitPrice))}</b></div>)}</div><div className="mt-5 space-y-2 text-sm"><p className="flex justify-between"><span>Subtotal</span><b>{money(subtotal)}</b></p><p className="flex justify-between"><span>Tax</span><b>{money(Number(form.tax))}</b></p><p className="flex justify-between"><span>Discount</span><b>-{money(Number(form.discount))}</b></p><p className="flex justify-between text-xl font-black"><span>Total</span><span>{money(total)}</span></p></div></div></aside></section>
  <section className="card overflow-hidden"><div className="p-5 font-black">Invoice History</div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="table-head"><tr><th className="p-3">Invoice</th><th className="p-3">Client</th><th className="p-3">Status</th><th className="p-3">Total</th><th className="p-3">Created</th><th className="p-3">Downloads</th><th className="p-3">Action</th></tr></thead><tbody>{invoices.length?invoices.map(inv=><tr key={inv._id} className="border-t border-white/10"><td className="p-3 font-bold text-[#8ACBD0]">{inv.invoiceNumber}</td><td className="p-3">{inv.clientName}</td><td className="p-3"><span className="badge capitalize">{inv.status}</span></td><td className="p-3">{money(inv.total)}</td><td className="p-3">{new Date(inv.createdAt).toLocaleDateString()}</td><td className="flex gap-2 p-3"><button onClick={()=>downloadBlob(`/invoices/${inv._id}/pdf`,`${inv.invoiceNumber}.pdf`)} className="btn-secondary px-3 py-2"><Download size={14}/> PDF</button><button onClick={()=>downloadBlob(`/invoices/${inv._id}/xlsx`,`${inv.invoiceNumber}.xlsx`)} className="btn-secondary px-3 py-2"><FileSpreadsheet size={14}/> Excel</button><button onClick={()=>window.print()} className="btn-secondary px-3 py-2"><Printer size={14}/></button></td><td className="p-3"><button onClick={()=>remove(inv._id)} className="btn-danger"><Trash2 size={14}/></button></td></tr>):<tr><td colSpan={7} className="p-6 text-slate-400">No invoices yet.</td></tr>}</tbody></table></div></section></div>
}
