import { useEffect, useState } from 'react';
import { api } from '../lib/api';

export default function Payroll() {
  const [employees, setEmployees] = useState<any[]>([]);
  const [payrolls, setPayrolls] = useState<any[]>([]);
  const [employeeForm, setEmployeeForm] = useState({ name: '', email: '', department: '', role: '', salary: '' });
  const [payrollForm, setPayrollForm] = useState({ employee: '', month: '2026-05', baseSalary: '', bonuses: '0', deductions: '0', tax: '0' });
  const load = () => { api.get('/employees').then(r=>setEmployees(r.data.data)); api.get('/payrolls').then(r=>setPayrolls(r.data.data.items)); };
  useEffect(load, []);
  async function addEmployee(e:any){ e.preventDefault(); const res = await api.post('/employees',{...employeeForm,salary:Number(employeeForm.salary)}); setEmployeeForm({name:'',email:'',department:'',role:'',salary:''}); setPayrollForm({...payrollForm, employee: res.data.data._id, baseSalary: String(res.data.data.salary)}); load(); }
  async function runPayroll(e:any){ e.preventDefault(); await api.post('/payrolls',{...payrollForm,baseSalary:Number(payrollForm.baseSalary),bonuses:Number(payrollForm.bonuses),deductions:Number(payrollForm.deductions),tax:Number(payrollForm.tax)}); load(); }
  return <div><h1 className="text-3xl font-black">Payroll</h1><p className="mt-2 text-slate-400">Manage employees, salaries, deductions, taxes and payroll history.</p>
    <div className="mt-6 grid gap-4 xl:grid-cols-2"><form onSubmit={addEmployee} className="card grid gap-3 p-5"><h2 className="font-bold">Add Employee</h2><input className="input" placeholder="Name" value={employeeForm.name} onChange={e=>setEmployeeForm({...employeeForm,name:e.target.value})}/><input className="input" placeholder="Email" value={employeeForm.email} onChange={e=>setEmployeeForm({...employeeForm,email:e.target.value})}/><input className="input" placeholder="Department" value={employeeForm.department} onChange={e=>setEmployeeForm({...employeeForm,department:e.target.value})}/><input className="input" placeholder="Role" value={employeeForm.role} onChange={e=>setEmployeeForm({...employeeForm,role:e.target.value})}/><input className="input" placeholder="Salary" value={employeeForm.salary} onChange={e=>setEmployeeForm({...employeeForm,salary:e.target.value})}/><button className="btn">Save Employee</button></form>
    <form onSubmit={runPayroll} className="card grid gap-3 p-5"><h2 className="font-bold">Run Payroll</h2><select className="input" value={payrollForm.employee} onChange={e=>{const emp=employees.find(x=>x._id===e.target.value); setPayrollForm({...payrollForm,employee:e.target.value,baseSalary:String(emp?.salary||'')})}}><option className="text-black" value="">Select employee</option>{employees.map(e=><option className="text-black" value={e._id} key={e._id}>{e.name}</option>)}</select><input className="input" placeholder="Month" value={payrollForm.month} onChange={e=>setPayrollForm({...payrollForm,month:e.target.value})}/><input className="input" placeholder="Base Salary" value={payrollForm.baseSalary} onChange={e=>setPayrollForm({...payrollForm,baseSalary:e.target.value})}/><input className="input" placeholder="Bonus" value={payrollForm.bonuses} onChange={e=>setPayrollForm({...payrollForm,bonuses:e.target.value})}/><input className="input" placeholder="Deductions" value={payrollForm.deductions} onChange={e=>setPayrollForm({...payrollForm,deductions:e.target.value})}/><input className="input" placeholder="Tax" value={payrollForm.tax} onChange={e=>setPayrollForm({...payrollForm,tax:e.target.value})}/><button className="btn">Create Payslip</button></form></div>
    <div className="card mt-6 overflow-hidden"><table className="w-full text-left"><thead className="bg-white/10"><tr><th className="p-4">Employee</th><th>Month</th><th>Net Pay</th><th>Status</th></tr></thead><tbody>{payrolls.map(p=><tr key={p._id} className="border-t border-white/10"><td className="p-4">{p.employee?.name}</td><td>{p.month}</td><td>₦{p.netPay?.toLocaleString()}</td><td>{p.status}</td></tr>)}</tbody></table></div>
  </div>;
}
