import { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { Download, FileSpreadsheet, Printer, QrCode, Trash2 } from 'lucide-react';
import { api } from '../lib/api';
const money=(n:number)=>`₦${Number(n||0).toLocaleString()}`; const today=()=>new Date().toISOString().slice(0,10);
function downloadBlob(url:string, name:string){api.get(url,{responseType:'blob'}).then(res=>{const blob=new Blob([res.data]); const link=document.createElement('a'); link.href=URL.createObjectURL(blob); link.download=name; link.click(); URL.revokeObjectURL(link.href);});}
export default function Receipts(){
  const [receipts,setReceipts]=useState<any[]>([]); const [invoices,setInvoices]=useState<any[]>([]); const [error,setError]=useState(''); const [saving,setSaving]=useState(false);
  const [form,setForm]=useState({paidBy:'',amount:'',paymentMethod:'Transfer',issuedAt:today(),invoiceId:'',notes:''});
  async function load(){try{const [r,i]=await Promise.all([api.get('/receipts'),api.get('/invoices?limit=100')]);setReceipts(r.data.data||[]);setInvoices(i.data.data.items||[])}catch(e:any){setError(e?.response?.data?.message||'Unable to load receipts.')}}
  useEffect(()=>{load()},[]);
  async function save(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');try{const amount=Number(form.amount); if(!form.paidBy) throw new Error('Customer name is required.'); if(amount<=0) throw new Error('Enter a valid payment amount.'); await api.post('/receipts',{...form,amount,invoiceId:form.invoiceId||undefined}); setForm({paidBy:'',amount:'',paymentMethod:'Transfer',issuedAt:today(),invoiceId:'',notes:''}); await load()}catch(err:any){setError(err?.response?.data?.message||err.message)}finally{setSaving(false)}}
  async function remove(id:string){if(confirm('Delete this receipt?')){await api.delete(`/receipts/${id}`);load()}}
  const total=receipts.reduce((s,r)=>s+Number(r.amount||0),0);
  return <div className="space-y-6"><div><p className="text-sm uppercase tracking-[0.3em] text-[#8ACBD0]">Collections</p><h1 className="mt-2 text-3xl font-black md:text-4xl">Receipt Management</h1><p className="mt-2 max-w-3xl text-slate-300">Generate customer payment receipts, attach them to invoices, export as PDF or Excel, and store all records in MongoDB.</p></div>{error&&<p className="rounded-2xl bg-red-500/15 p-4 text-red-100">{error}</p>}
  <section className="grid gap-4 md:grid-cols-3"><Metric title="Receipts" value={receipts.length}/><Metric title="Total Collected" value={money(total)}/><Metric title="Payment Methods" value="Cash · Transfer · Card · POS"/></section>
  <section className="grid gap-6 xl:grid-cols-[.9fr_1.1fr]"><motion.form initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} onSubmit={save} className="card p-5"><h2 className="text-xl font-black">Generate Receipt</h2><div className="mt-4 grid gap-3"><input className="input" placeholder="Customer name" value={form.paidBy} onChange={e=>setForm({...form,paidBy:e.target.value})}/><input className="input" type="number" placeholder="Amount paid" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/><select className="input" value={form.paymentMethod} onChange={e=>setForm({...form,paymentMethod:e.target.value})}><option>Cash</option><option>Transfer</option><option>Card</option><option>POS</option></select><select className="input" value={form.invoiceId} onChange={e=>setForm({...form,invoiceId:e.target.value})}><option value="">Link invoice optional</option>{invoices.map((i:any)=><option key={i._id} value={i._id}>{i.invoiceNumber} · {i.clientName}</option>)}</select><input className="input" type="date" value={form.issuedAt} onChange={e=>setForm({...form,issuedAt:e.target.value})}/><textarea className="input min-h-24" placeholder="Notes" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></div><button disabled={saving} className="btn mt-4">Save Receipt</button></motion.form><div className="card p-5"><h2 className="text-xl font-black">Receipt Preview</h2><div className="mt-4 rounded-[2rem] bg-[#EFE3CA] p-5 text-[#170C79]"><div className="flex justify-between"><div><p className="text-xs font-black uppercase tracking-widest">ALAT Financial System</p><h3 className="text-2xl font-black">PAYMENT RECEIPT</h3></div><QrCode/></div><div className="mt-6 space-y-3 text-sm"><p className="flex justify-between"><span>Customer</span><b>{form.paidBy||'Customer name'}</b></p><p className="flex justify-between"><span>Amount</span><b>{money(Number(form.amount))}</b></p><p className="flex justify-between"><span>Payment Method</span><b>{form.paymentMethod}</b></p><p className="flex justify-between"><span>Date</span><b>{form.issuedAt}</b></p></div></div></div></section>
  <section className="card overflow-hidden"><div className="p-5 font-black">Receipt History</div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="table-head"><tr><th className="p-3">Receipt</th><th className="p-3">Customer</th><th className="p-3">Amount</th><th className="p-3">Method</th><th className="p-3">Date</th><th className="p-3">Downloads</th><th className="p-3">Action</th></tr></thead><tbody>{receipts.length?receipts.map((r:any)=><tr key={r._id} className="border-t border-white/10"><td className="p-3 font-bold text-[#8ACBD0]">{r.receiptNumber}</td><td className="p-3">{r.paidBy}</td><td className="p-3">{money(r.amount)}</td><td className="p-3">{r.paymentMethod}</td><td className="p-3">{new Date(r.issuedAt||r.createdAt).toLocaleDateString()}</td><td className="flex gap-2 p-3"><button onClick={()=>downloadBlob(`/receipts/${r._id}/pdf`,`${r.receiptNumber}.pdf`)} className="btn-secondary px-3 py-2"><Download size={14}/> PDF</button><button onClick={()=>downloadBlob(`/receipts/${r._id}/xlsx`,`${r.receiptNumber}.xlsx`)} className="btn-secondary px-3 py-2"><FileSpreadsheet size={14}/> Excel</button><button onClick={()=>window.print()} className="btn-secondary px-3 py-2"><Printer size={14}/></button></td><td className="p-3"><button onClick={()=>remove(r._id)} className="btn-danger"><Trash2 size={14}/></button></td></tr>):<tr><td className="p-6 text-slate-400" colSpan={7}>No receipts yet.</td></tr>}</tbody></table></div></section></div>
}
function Metric({title,value}:any){return <div className="card p-5"><p className="text-sm text-slate-300">{title}</p><h3 className="mt-2 text-2xl font-black text-[#8ACBD0]">{value}</h3></div>}
